# Generated by Django 5.0.6 on 2024-09-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("publication_date", models.DateField()),
                ("source_name", models.CharField(max_length=255)),
                ("feedback", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-publication_date"],
            },
        ),
    ]
