# Generated by Django 5.0.6 on 2024-09-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsfeedback",
            name="ismegaproject",
            field=models.CharField(default="Yes", max_length=10),
        ),
    ]
