# Generated by Django 5.0.6 on 2024-09-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeedback", "0002_newsfeedback_ismegaproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsfeedback",
            name="contentstatus",
            field=models.CharField(default="Clean", max_length=10),
        ),
    ]
