# Generated by Django 5.0.6 on 2026-02-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeedback", "0003_newsfeedback_contentstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "news_url",
                    models.URLField(default="www.megaproject.com", max_length=500),
                ),
                ("publication_date", models.DateField()),
                ("source_name", models.CharField(max_length=255)),
                (
                    "content",
                    models.TextField(default="Content not found", max_length=100000),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="newsfeedback",
            name="contentstatus",
            field=models.CharField(default="Clean", max_length=50),
        ),
    ]
